### ISSUE TITLE
system76-dkms and acpi-dkms return post-scripts errors on Fedora 37 Silverblue

### ISSUE THREAD

**Issue by candied487** [szydell/system76-dkms#19]
**Distribution (run `cat /etc/os-release`):** Fedora 37 Silverblue
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:** error: Running %post for system76-dkms: bwrap(/bin/sh): Child process killed by signal 8; run `journalctl -t 'rpm-ostree(system76-dkms.post)'` for more information
Error! No write access to DKMS tree at /var/lib/dkms
mkdir: Cannot create directory '/var/lib/dkms/: Read-only file system
...
Build halted

**Steps to reproduce (if you know):**
download and add /etc/yum.repos.d/szydell-system76.repo (or download rpm packages manually from https://download.copr.fedorainfracloud.org/results/szydell/system76/fedora-37-x86_64/05604027-system76-dkms/system76-dkms-1.0.14-4.x86_64.rpm)

rpm-ostree install system76-dkms system76-acpi-dkms

**Expected behavior:** should not return an error. worked OK on Fedora 37 stable when I tested otherwise

**Other Notes:**

**Comment by szydell** [comment]
Packages in COPR are not built for Silverblue. I don't know if Fedora will support such builds on COPR.
